### ISSUE TITLE
Cannot upload to Graylog2 beta2

### ISSUE THREAD

**Issue by ovizii** [jkumar2001/graylog-generic-syslog#1]
I go to SYSTEM => Content Packs => Import select this content pack click upload and nothing happens.

**Comment by Spafbi** [comment]
@ovizii - I also could not add this as a content pack, but I was able to use it to import the extractors for an existing input.

**Comment by jkumar2001** [comment]
Updated the content pack with valid inputs, should import into Graylog properly now.

**Comment by ovizii** [comment]
Thanks it worked now but it seems activating it creates a Syslog UDPO 5140 input and I already have one so I deleted mine, started yours, works all good now.

Many thanks!
